name: energy_carbon_footprint_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - scipy
  - jupyterlab
  - pip
  - pip:
    - coolprop # An open-source package that contains thermophysical properties for many substances
